apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: signoz
  namespace: monitoring
spec:
  interval: 5m0s
  chart: signoz
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: signoz
  version: 0.79.*
